# Generated by Django 5.0.6 on 2024-06-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_alter_fileupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='sheet_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
